#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE auth_db;
  CREATE DATABASE catalog_db;
  CREATE DATABASE loan_db;
  CREATE DATABASE report_db;
  GRANT ALL PRIVILEGES ON DATABASE auth_db    TO $POSTGRES_USER;
  GRANT ALL PRIVILEGES ON DATABASE catalog_db TO $POSTGRES_USER;
  GRANT ALL PRIVILEGES ON DATABASE loan_db    TO $POSTGRES_USER;
  GRANT ALL PRIVILEGES ON DATABASE report_db  TO $POSTGRES_USER;
EOSQL
